"""lingua/en.py — English texts"""
TESTI = {
    # App
    "app_titolo": "GDR Map Creator & Session Manager",
    "versione": "Version",
    # Lingua
    "scegli_lingua": "Scegli la lingua / Choose your language",
    "lingua_it": "🇮🇹  Italiano",
    "lingua_en": "🇬🇧  English",
    "continua": "Continue",
    # Login
    "login_titolo": "Login",
    "username": "Username",
    "password": "Password",
    "accedi": "Login",
    "registrati": "Register",
    "crea_account": "Create account",
    "conferma_password": "Confirm password",
    "ruolo": "Role",
    "ruolo_player": "Player (free)",
    "ruolo_dm": "Dungeon Master (subscription required)",
    "errore": "Error",
    "campo_obbligatorio": "Required field",
    "credenziali_non_valide": "Invalid credentials.",
    "password_min": "Password must be at least {n} characters.",
    "username_min": "Username must be at least 3 characters.",
    "username_in_uso": "Username '{u}' is already taken.",
    "password_non_coincidono": "Passwords do not match.",
    "account_creato": "Account created",
    "account_creato_msg": "Account '{u}' created successfully!\nLogin with your credentials.",
    "esci": "Logout",
    # Dashboard DM
    "benvenuto": "Welcome, {u}",
    "abbonamento_attivo": "✓ Subscription active",
    "abbonamento_non_attivo": "✗ Subscription not active",
    "i_miei_mondi": "🌍  My Worlds",
    "nuovo_mondo": "➕  New World",
    "modifica_selezionato": "✏️  Edit selected",
    "nessun_mondo": "No worlds yet — click '➕ New World' to start",
    "shop_dm": "🛒  DM Shop",
    # Dashboard Player
    "sessioni_disponibili": "Available sessions:",
    "nessuna_sessione": "No open sessions at the moment",
    "entra_sessione": "▶  Join session",
    "la_mia_scheda": "📋  My character sheet",
    "shop": "🛒  Shop",
    "aggiorna": "↻  Refresh",
    # Editor mondo
    "modifica_mondo": "Edit world",
    "crea_mondo": "Create new world",
    "nome": "Name",
    "lore": "Lore / world history:",
    "descrizione": "Session description:",
    "salva": "💾  Save",
    "annulla": "Cancel",
    "mappe": "🗺️ Maps",
    "informazioni": "🌍 Information",
    "nuova_mappa": "➕  New map",
    "apri_editor": "🗺️  Open Editor",
    "nessuna_mappa": "No maps — click '➕ New map' to create one",
    "nome_mappa": "Map name:",
    "salva_prima": "Save the world before adding maps.",
    "seleziona_mappa": "Select a map from the list.",
    "seleziona_mondo": "Select a world from the list.",
    "mondo_salvato": "World '{n}' saved.",
    # Editor mappa
    "terreni": "Terrain",
    "oggetti": "Objects",
    "pavimenti": "Floors",
    "npc_tab": "NPC",
    "nemici_tab": "Enemies",
    "rotazione": "Rot:",
    "salvata": "✓ Saved",
    "salva_s": "💾 Save (S)",
    "torna_su": "← Back (⌫)",
    "zoom": "Zoom",
    "pan": "Ctrl+drag: pan",
    "rotellina": "Scroll: zoom",
    "master": "MASTER",
    "player": "PLAYER",
    "pavimento": "Floor",
    "terreno_lbl": "Terrain",
    "oggetto_lbl": "Object",
    "scroll_su": "▲ scroll",
    "scroll_giu": "▼ scroll",
    # Menu contestuale
    "modifica_oggetto": "✏️  Edit object",
    "cambia_skin": "🎨  Change skin",
    "entra_sottolivello": "🚪  Enter sublevel",
    "crea_sottolivello": "🏗️  Create sublevel",
    "rimuovi_oggetto": "🗑️  Remove object",
    "rimuovi_terreno": "🗑️  Remove terrain",
    # NPC
    "npc_titolo": "NPC",
    "nemico_titolo": "Enemy",
    "genera_npc": "🎲 Generate random NPC",
    "genera_nemico": "🎲 Generate random Enemy",
    "scheda_npc": "NPC Sheet",
    "scheda_nemico": "Enemy Sheet",
    "nome_npc": "Name",
    "razza": "Race",
    "classe": "Class",
    "tipo": "Type",
    "pf": "Hit Points",
    "ca": "Armor Class",
    "for": "Strength",
    "des": "Dexterity",
    "cos": "Constitution",
    "int": "Intelligence",
    "sag": "Wisdom",
    "car": "Charisma",
    "modifica_scheda": "✏️ Edit sheet",
    "piazza_sulla_mappa": "📍 Place on map",
    "nessun_npc": "No NPC — click 'Generate' to create one",
    "nessun_nemico": "No Enemy — click 'Generate' to create one",
    # Shop
    "shop_titolo": "DM Shop — Assets, Maps & Manuals",
    "shop_player_titolo": "Shop — Skins & Content",
    "chiudi": "Close",
    "acquista": "Buy",
    "gia_acquistato": "✓ Already owned",
    "i_miei_acquisti": "📦 My purchases",
    "nessun_acquisto": "No purchases yet.",
    "conferma_acquisto": "Confirm purchase",
    "carica_in_mondo": "📥  Load into world",
    "scegli_mondo": "Load '{n}' into which world?",
    "nessun_mondo_shop": "You have no worlds yet.\nCreate a world from the dashboard first.",
    "mappa_caricata": "Map loaded!",
}
