"""lingua/it.py — Testi in italiano"""
TESTI = {
    # App
    "app_titolo": "GDR Map Creator & Session Manager",
    "versione": "Versione",
    # Lingua
    "scegli_lingua": "Scegli la lingua / Choose your language",
    "lingua_it": "🇮🇹  Italiano",
    "lingua_en": "🇬🇧  English",
    "continua": "Continua",
    # Login
    "login_titolo": "Accesso",
    "username": "Nome utente",
    "password": "Password",
    "accedi": "Accedi",
    "registrati": "Registrati",
    "crea_account": "Crea account",
    "conferma_password": "Conferma password",
    "ruolo": "Ruolo",
    "ruolo_player": "Player (gratuito)",
    "ruolo_dm": "Dungeon Master (abbonamento richiesto)",
    "errore": "Errore",
    "campo_obbligatorio": "Campo obbligatorio",
    "credenziali_non_valide": "Credenziali non valide.",
    "password_min": "La password deve avere almeno {n} caratteri.",
    "username_min": "Il nome utente deve avere almeno 3 caratteri.",
    "username_in_uso": "Il nome utente '{u}' è già in uso.",
    "password_non_coincidono": "Le password non coincidono.",
    "account_creato": "Account creato",
    "account_creato_msg": "Account '{u}' creato con successo!\nAccedi con le tue credenziali.",
    "esci": "Esci",
    # Dashboard DM
    "benvenuto": "Benvenuto, {u}",
    "abbonamento_attivo": "✓ Abbonamento attivo",
    "abbonamento_non_attivo": "✗ Abbonamento non attivo",
    "i_miei_mondi": "🌍  I miei Mondi",
    "nuovo_mondo": "➕  Nuovo mondo",
    "modifica_selezionato": "✏️  Modifica selezionato",
    "nessun_mondo": "Nessun mondo ancora — clicca '➕ Nuovo mondo' per iniziare",
    "shop_dm": "🛒  Shop DM",
    # Dashboard Player
    "sessioni_disponibili": "Sessioni disponibili:",
    "nessuna_sessione": "Nessuna sessione aperta al momento",
    "entra_sessione": "▶  Entra nella sessione",
    "la_mia_scheda": "📋  La mia scheda",
    "shop": "🛒  Shop",
    "aggiorna": "↻  Aggiorna ora",
    # Editor mondo
    "modifica_mondo": "Modifica mondo",
    "crea_mondo": "Crea nuovo mondo",
    "nome": "Nome",
    "lore": "Lore / storia del mondo:",
    "descrizione": "Descrizione sessioni:",
    "salva": "💾  Salva",
    "annulla": "Annulla",
    "mappe": "🗺️ Mappe",
    "informazioni": "🌍 Informazioni",
    "nuova_mappa": "➕  Nuova mappa",
    "apri_editor": "🗺️  Apri Editor",
    "nessuna_mappa": "Nessuna mappa — clicca '➕ Nuova mappa' per crearne una",
    "nome_mappa": "Nome della mappa:",
    "salva_prima": "Salva il mondo prima di aggiungere mappe.",
    "seleziona_mappa": "Seleziona una mappa dalla lista.",
    "seleziona_mondo": "Seleziona un mondo dalla lista.",
    "mondo_salvato": "Mondo '{n}' salvato.",
    # Editor mappa
    "terreni": "Terreni",
    "oggetti": "Oggetti",
    "pavimenti": "Pavimenti",
    "npc_tab": "NPC",
    "nemici_tab": "Nemici",
    "rotazione": "Rot:",
    "salvata": "✓ Salvata",
    "salva_s": "💾 Salva (S)",
    "torna_su": "← Torna su (⌫)",
    "zoom": "Zoom",
    "pan": "Ctrl+trascina: pan",
    "rotellina": "Rotellina: zoom",
    "master": "MASTER",
    "player": "PLAYER",
    "pavimento": "Pavimento",
    "terreno_lbl": "Terreno",
    "oggetto_lbl": "Oggetto",
    "scroll_su": "▲ scroll",
    "scroll_giu": "▼ scroll",
    # Menu contestuale
    "modifica_oggetto": "✏️  Modifica oggetto",
    "cambia_skin": "🎨  Cambia skin",
    "entra_sottolivello": "🚪  Entra nel sottolivello",
    "crea_sottolivello": "🏗️  Crea sottolivello",
    "rimuovi_oggetto": "🗑️  Rimuovi oggetto",
    "rimuovi_terreno": "🗑️  Rimuovi terreno",
    # NPC
    "npc_titolo": "NPC",
    "nemico_titolo": "Nemico",
    "genera_npc": "🎲 Genera NPC casuale",
    "genera_nemico": "🎲 Genera Nemico casuale",
    "scheda_npc": "Scheda NPC",
    "scheda_nemico": "Scheda Nemico",
    "nome_npc": "Nome",
    "razza": "Razza",
    "classe": "Classe",
    "tipo": "Tipo",
    "pf": "Punti Ferita",
    "ca": "Classe Armatura",
    "for": "Forza",
    "des": "Destrezza",
    "cos": "Costituzione",
    "int": "Intelligenza",
    "sag": "Saggezza",
    "car": "Carisma",
    "modifica_scheda": "✏️ Modifica scheda",
    "piazza_sulla_mappa": "📍 Piazza sulla mappa",
    "nessun_npc": "Nessun NPC — clicca 'Genera' per crearne uno",
    "nessun_nemico": "Nessun Nemico — clicca 'Genera' per crearne uno",
    # Shop
    "shop_titolo": "Shop DM — Asset, Mappe e Manuali",
    "shop_player_titolo": "Shop — Skin e Contenuti",
    "chiudi": "Chiudi",
    "acquista": "Acquista",
    "gia_acquistato": "✓ Già acquistato",
    "i_miei_acquisti": "📦 I miei acquisti",
    "nessun_acquisto": "Nessun acquisto ancora.",
    "conferma_acquisto": "Conferma acquisto",
    "carica_in_mondo": "📥  Carica in un mondo",
    "scegli_mondo": "In quale mondo vuoi caricare '{n}'?",
    "nessun_mondo_shop": "Non hai ancora nessun mondo.\nCrea prima un mondo dalla dashboard.",
    "mappa_caricata": "Mappa caricata!",
}
